Updated homer-tools and homer-upgrade

diff --git a/bin/homer-tools b/bin/homer-tools
--- a/bin/homer-tools
+++ b/bin/homer-tools
@@ -62,7 +62,7 @@ source "$HOMER_PATH/share/homer/cli.zsh"
 
 echo "--- Installing required packages -------------------------------"
 if type "pacman" > /dev/null; then
-  sudo pacman -S zsh yay git meld curl ripgrep tmux xsel xclip rust vim cmake autoconf
+  sudo pacman -S zsh yay git meld curl ripgrep tmux xsel xclip rust vim cmake autoconf gcc fakeroot patch base-devel
   # TODO: sudo yay -S <nice_to_have_like_youtube-dl_etc>
 elif type "apt" > /dev/null; then
   sudo apt install zsh wget meld curl tmux xsel xclip rustc vim make cmake autoconf python3 python3-pip texinfo libgtk-3-dev libwebkit2gtk-4.0-dev gnutls-bin libtiff-dev libgif-dev libjpeg-dev libxpm-dev libgnutls28-dev libncurses-dev
@@ -180,6 +180,10 @@ if [ $? -eq 0 ]; then
   cd $HOME/etc/emacs-dev || exit 1
   git checkout emacs-27
   make clean && ./autogen.sh && ./configure --with-modules --without-xft --with-xwidgets --with-gconf --with-cairo --with-harfbuzz && make
+  if [ ! $? -eq 0 ]; then
+    echo "ERROR: Emacs install failed"
+    exit 1
+  fi
   popd
 else
   echo "--- Skipping: Target directory already exists and is not empty: $HOME/etc/emacs-dev"
@@ -247,7 +251,7 @@ fi
 # svls
 echo "--- Installing svls -------------------------------"
 if type "cargo" > /dev/null; then
-  pip2 install jedi
+  pip install jedi
   cargo install svls
 else
   echo "Skipping: No cargo command found -----------------------"
@@ -266,6 +270,7 @@ else
   echo "--- Skipping: No yay command found -----------------"
 fi
 
+sudo locale-gen
 
 ##############################################################
 # tmux tpm plugin manager
@@ -275,15 +280,17 @@ git clone https://github.com/tmux-plugins/tpm $HOME/.tmux/plugins/tpm
 
 echo "--- Installations finished ------------------------------"
 echo "--- Things to do manually:"
-echo "--- 1) Open $XDG_CONFIG_HOME/zsh/.p10k.zsh and insert the following modelines under 'typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=('\n
+echo "--- 1) Reboot to make sure everyhing is reloaded"
+echo "--- 2) Start a new terminal and run p10k configure"
+echo "--- 3) Open $XDG_CONFIG_HOME/zsh/.p10k.zsh and insert the following modelines under 'typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=('\n
 	timewarrior\n
 	quartus_env\n
 	vivado_env\n
 	questa_env\n
 	vcs_env"
-echo "--- 2) In .p10k.zsh add hg to POWERLEVEL9K_VCS_BACKENDS"
-echo "--- 3) Open $XDG_CONFIG_HOME/tmux/.tmux.conf and install plugins with prefix + I, prefix + U"
-echo "--- 4) Restart open terminals"
-echo "--- 5) Start Tmux and reload Tmux config file"
-echo "--- 6) Start Spacemacs for the first time and a ~/.config/spacemacs/.spacemacs.env will be generated. Verify the contents."
+echo "--- 4) In .p10k.zsh add hg to POWERLEVEL9K_VCS_BACKENDS"
+echo "--- 5) Start tmux with tmuxf and install plugins with prefix + I, prefix + U. It might take some time before something happens."
+echo "--- 6) Restart open terminals"
+echo "--- 7) Start Tmux and reload Tmux config file"
+echo "--- 8) Start Spacemacs for the first time and a ~/.config/spacemacs/.spacemacs.env will be generated. Verify the contents."
 
diff --git a/bin/homer-upgrade b/bin/homer-upgrade
--- a/bin/homer-upgrade
+++ b/bin/homer-upgrade
@@ -103,6 +103,10 @@ pushd .
 cd $HOME/etc/emacs-dev || exit 1
 git pull
 make clean && ./autogen.sh && ./configure --with-modules --without-xft --with-xwidgets --with-gconf --with-cairo --with-harfbuzz && make
+if [ ! $? -eq 0 ]; then
+  echo "ERROR: Emacs install failed"
+  exit 1
+fi
 popd
 
 
